services:
  yolopv2-stream:
    build: .
    runtime: nvidia
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    ports:
      - "5000:5000"
    environment:
      - VIDEO_SOURCE=/app/sample.mp4
      - DEVICE=0
      - PYTHONUNBUFFERED=1
    volumes:
      - ./weights:/app/data/weights
      - ./app.py:/app/app.py
    restart: unless-stopped
