services:
  dashcam:
    build: .
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    ports:
      - "5001:5001"
    environment:
      - VIDEO_SOURCE=/dev/video0
      # - DEV_VIDEO_PATH=/app/recordings/dashcam_20260521_105410.avi # Uncomment to test with a looping recorded video
      - DEVICE=0
      - PYTHONUNBUFFERED=1
    volumes:
      - ./recordings:/app/recordings
      - ../weights:/app/data/weights
      - ./dashcam.py:/app/dashcam.py
      - ./yolop_detector.py:/app/yolop_detector.py
      - ./models:/app/models
      - ./templates:/app/templates
    # WARNING: If your camera is physically UNPLUGGED, you MUST comment out the two lines below, 
    # otherwise Docker will crash trying to find /dev/video0.
    devices:
      - /dev/video0:/dev/video0
    restart: unless-stopped
